
environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Debug

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Retail

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      buildcfg: debug64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      buildcfg: release64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      buildcfg: retail64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
      buildcfg: debug64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
      buildcfg: release64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
      buildcfg: retail64
    
shallow_clone: true

install:
- git submodule init
- git submodule update

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
  
    init:
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp    rapp
      - git clone --depth 1 https://github.com/RudjiGames/rprof   rprof
      - git clone --depth 1 https://github.com/RudjiGames/build   build
      - git clone --depth 1 https://github.com/RudjiGames/rbase   rbase
      - git clone --depth 1 https://github.com/bkaradzic/bx.git   bx
      - git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg
      - git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
     
    install:
      - build\tools\bin\windows\genie.exe --file=rprof\genie\genie.lua vs2019
      
    build: ../.build/windows/vs2019/rprof/projects/rprof.sln

# ======================================
#      Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - sudo apt update -y && sudo apt install -y xorg libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libegl1-mesa-dev
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp  rapp
      - git clone --depth 1 https://github.com/RudjiGames/rprof rprof
      - git clone --depth 1 https://github.com/RudjiGames/build build
      - git clone --depth 1 https://github.com/RudjiGames/rbase rbase
      - git clone --depth 1 https://github.com/bkaradzic/bx     bx
      - git clone --depth 1 https://github.com/bkaradzic/bimg   bimg
      - git clone --depth 1 https://github.com/bkaradzic/bgfx   bgfx
      - git clone --depth 1 https://github.com/glfw/glfw        glfw
      - git clone --depth 1 https://github.com/bkaradzic/GENie  GENie		# build GENie from source: `GLIBC_2.29' not found
      - cd GENie && make && cd ..
      - mkdir glfwbuild && cd glfwbuild && cmake ../glfw -DGLFW_BUILD_TESTS=OFF && make -j4 && sudo make install && cd ..

    install:
      - ./GENie/bin/linux/genie --file=rprof/genie/genie.lua --gcc=linux-gcc-9 gmake
  
    build_script:
      - cd ./.build/linux/gcc-9/rprof/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp    rapp
      - git clone --depth 1 https://github.com/RudjiGames/rprof   rprof
      - git clone --depth 1 https://github.com/RudjiGames/build   build
      - git clone --depth 1 https://github.com/RudjiGames/rbase   rbase
      - git clone --depth 1 https://github.com/bkaradzic/bx.git   bx
      - git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg
      - git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
    
    install:
      - ./build/tools/bin/darwin/genie --file=rprof/genie/genie.lua --gcc=osx gmake
    
    build_script:
      - cd ./.build/osx/clang/rprof/projects/
      - make config=${buildcfg}
